export {
  DEFAULT_CANVAS_ACCELERATED_NUDGE,
  DEFAULT_CANVAS_DRAG_THRESHOLD,
  DEFAULT_CANVAS_INTERACTION_CAPABILITIES,
  DEFAULT_CANVAS_MIN_SIZE,
  DEFAULT_CANVAS_NUDGE,
  DEFAULT_CANVAS_SHORTCUTS,
  clientDeltaToCanvasDelta,
  clientPointToCanvasPoint,
  constrainCanvasDragDelta,
  createCanvasGestureController,
  createCanvasInteractionCore,
  createCanvasShortcutRegistry,
  hasCrossedCanvasDragThreshold,
  resizeCanvasRect,
  resolveCanvasEscape,
  resolveCanvasNudge,
  resolveCanvasShortcut,
  resolveCanvasTextActivation,
  shouldDuplicateCanvasDrag,
  type CanvasCommand,
  type CanvasCommandDispatchResult,
  type CanvasCommandId,
  type CanvasDragPolicy,
  type CanvasDuplicateModifier,
  type CanvasEscapeBehavior,
  type CanvasEscapeInput,
  type CanvasEscapeResult,
  type CanvasGesture,
  type CanvasGestureAdapter,
  type CanvasGestureAdapterResult,
  type CanvasGestureBeginResult,
  type CanvasGestureCancelResult,
  type CanvasGestureControllerConfig,
  type CanvasGestureEndResult,
  type CanvasGestureKind,
  type CanvasGesturePhase,
  type CanvasGesturePointer,
  type CanvasGestureStart,
  type CanvasGestureState,
  type CanvasGestureUpdateResult,
  type CanvasMoveGesture,
  type CanvasMoveGestureStart,
  type CanvasInteractionAdapter,
  type CanvasInteractionCapabilities,
  type CanvasInteractionConfig,
  type CanvasModifiers,
  type CanvasNudgeInput,
  type CanvasNudgePolicy,
  type CanvasNudgeResult,
  type CanvasPoint,
  type CanvasRect,
  type CanvasResizeHandle,
  type CanvasResizeGesture,
  type CanvasResizeGestureStart,
  type CanvasResizeInput,
  type CanvasShortcut,
  type CanvasShortcutInput,
  type CanvasShortcutModifier,
  type CanvasShortcutRegistry,
  type CanvasSize,
  type CanvasTextActivation,
  type CanvasTextActivationInput,
  type CanvasTextActivationResult,
  type CanvasTextEditPolicy,
  type CanvasViewport,
} from "./canvas-interactions.js";
